version: '3.8'

services:
  website:
    build:
      context: .
      dockerfile: ./apps/website/Dockerfile
    ports:
      - "4200:4200"
    environment:
      - ORIGIN=http://localhost:4200

  proxy:
    build:
      context: ./infrastructure/proxy/development
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
